spring.application.name=FastFuriousAPI
#Habilita o console do H2 para acessarmos pelo navegador
spring.h2.console.enabled=true
#Define o caminho do banco na memória RAM
spring.datasource.url=jdbc:h2:mem:fastfuriousdb
spring.datasource.driverClassName=org.h2.Driver
#Usuário padrão do H2 
spring.datasource.username=sa
spring.datasource.password=

# Mostra o SQL no console (ajuda muito a ver as tabelas sendo criadas)
spring.jpa.show-sql=true
